# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QSizePolicy, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(800, 600)
        self.zaporizha = QLabel(Widget)
        self.zaporizha.setObjectName(u"zaporizha")
        self.zaporizha.setGeometry(QRect(80, 80, 624, 468))
        self.zaporizha.setLineWidth(0)
        self.zaporizha.setPixmap(QPixmap(u"region/zaporizha.png"))
        self.kherson = QLabel(Widget)
        self.kherson.setObjectName(u"kherson")
        self.kherson.setGeometry(QRect(80, 80, 624, 468))
        self.kherson.setMidLineWidth(5)
        self.kherson.setPixmap(QPixmap(u"region/kherson.png"))
        self.mykolaiv = QLabel(Widget)
        self.mykolaiv.setObjectName(u"mykolaiv")
        self.mykolaiv.setGeometry(QRect(80, 80, 624, 468))
        self.mykolaiv.setPixmap(QPixmap(u"region/mykolaiv.png"))
        self.odesa = QLabel(Widget)
        self.odesa.setObjectName(u"odesa")
        self.odesa.setGeometry(QRect(80, 80, 624, 468))
        self.odesa.setPixmap(QPixmap(u"region/odesa.png"))
        self.vinnytsia = QLabel(Widget)
        self.vinnytsia.setObjectName(u"vinnytsia")
        self.vinnytsia.setGeometry(QRect(80, 80, 624, 468))
        self.vinnytsia.setPixmap(QPixmap(u"region/vinnytsia.png"))
        self.khmelnytskyi = QLabel(Widget)
        self.khmelnytskyi.setObjectName(u"khmelnytskyi")
        self.khmelnytskyi.setGeometry(QRect(80, 80, 624, 468))
        self.khmelnytskyi.setPixmap(QPixmap(u"region/khmelnytskyi.png"))
        self.chernivts = QLabel(Widget)
        self.chernivts.setObjectName(u"chernivts")
        self.chernivts.setGeometry(QRect(80, 80, 624, 468))
        self.chernivts.setPixmap(QPixmap(u"region/chernivtsi.png"))
        self.ivanoFrankivsk = QLabel(Widget)
        self.ivanoFrankivsk.setObjectName(u"ivanoFrankivsk")
        self.ivanoFrankivsk.setGeometry(QRect(80, 80, 624, 468))
        self.ivanoFrankivsk.setPixmap(QPixmap(u"region/ivano-frankivsk.png"))
        self.zakarpattia = QLabel(Widget)
        self.zakarpattia.setObjectName(u"zakarpattia")
        self.zakarpattia.setGeometry(QRect(80, 80, 624, 468))
        self.zakarpattia.setPixmap(QPixmap(u"region/zakarpattia.png"))
        self.lviv = QLabel(Widget)
        self.lviv.setObjectName(u"lviv")
        self.lviv.setGeometry(QRect(80, 80, 624, 468))
        self.lviv.setPixmap(QPixmap(u"region/lviv.png"))
        self.ternopil = QLabel(Widget)
        self.ternopil.setObjectName(u"ternopil")
        self.ternopil.setGeometry(QRect(80, 80, 624, 468))
        self.ternopil.setPixmap(QPixmap(u"region/ternopil.png"))
        self.volyn = QLabel(Widget)
        self.volyn.setObjectName(u"volyn")
        self.volyn.setGeometry(QRect(80, 80, 624, 468))
        self.volyn.setPixmap(QPixmap(u"region/volyn.png"))
        self.rivne = QLabel(Widget)
        self.rivne.setObjectName(u"rivne")
        self.rivne.setGeometry(QRect(80, 80, 624, 468))
        self.rivne.setPixmap(QPixmap(u"region/rivne.png"))
        self.zhytomyr = QLabel(Widget)
        self.zhytomyr.setObjectName(u"zhytomyr")
        self.zhytomyr.setGeometry(QRect(80, 80, 624, 468))
        self.zhytomyr.setPixmap(QPixmap(u"region/zhytomyr.png"))
        self.kyivRegion = QLabel(Widget)
        self.kyivRegion.setObjectName(u"kyivRegion")
        self.kyivRegion.setGeometry(QRect(80, 80, 624, 468))
        self.kyivRegion.setPixmap(QPixmap(u"region/kyiv-region.png"))
        self.kyiv = QLabel(Widget)
        self.kyiv.setObjectName(u"kyiv")
        self.kyiv.setGeometry(QRect(80, 80, 624, 468))
        self.kyiv.setPixmap(QPixmap(u"region/kyiv.png"))
        self.chernihiv = QLabel(Widget)
        self.chernihiv.setObjectName(u"chernihiv")
        self.chernihiv.setGeometry(QRect(80, 80, 624, 468))
        self.chernihiv.setPixmap(QPixmap(u"region/chernihiv.png"))
        self.sumy = QLabel(Widget)
        self.sumy.setObjectName(u"sumy")
        self.sumy.setGeometry(QRect(80, 80, 624, 468))
        self.sumy.setPixmap(QPixmap(u"region/sumy.png"))
        self.poltava = QLabel(Widget)
        self.poltava.setObjectName(u"poltava")
        self.poltava.setGeometry(QRect(80, 80, 624, 468))
        self.poltava.setPixmap(QPixmap(u"region/poltava.png"))
        self.cherkasy = QLabel(Widget)
        self.cherkasy.setObjectName(u"cherkasy")
        self.cherkasy.setGeometry(QRect(80, 80, 624, 468))
        self.cherkasy.setPixmap(QPixmap(u"region/cherkasy.png"))
        self.kirovohrad = QLabel(Widget)
        self.kirovohrad.setObjectName(u"kirovohrad")
        self.kirovohrad.setGeometry(QRect(80, 80, 624, 468))
        self.kirovohrad.setPixmap(QPixmap(u"region/kirovohrad.png"))
        self.dnipropetrovsk = QLabel(Widget)
        self.dnipropetrovsk.setObjectName(u"dnipropetrovsk")
        self.dnipropetrovsk.setGeometry(QRect(80, 80, 624, 468))
        self.dnipropetrovsk.setPixmap(QPixmap(u"region/dnipropetrovsk.png"))
        self.kharkiv = QLabel(Widget)
        self.kharkiv.setObjectName(u"kharkiv")
        self.kharkiv.setGeometry(QRect(80, 80, 624, 468))
        self.kharkiv.setPixmap(QPixmap(u"region/kharkiv.png"))
        self.luhansk = QLabel(Widget)
        self.luhansk.setObjectName(u"luhansk")
        self.luhansk.setGeometry(QRect(80, 80, 624, 468))
        self.luhansk.setPixmap(QPixmap(u"region/luhansk.png"))
        self.donetsk = QLabel(Widget)
        self.donetsk.setObjectName(u"donetsk")
        self.donetsk.setGeometry(QRect(80, 80, 624, 468))
        self.donetsk.setPixmap(QPixmap(u"region/donetsk.png"))
        self.crimea = QLabel(Widget)
        self.crimea.setObjectName(u"crimea")
        self.crimea.setGeometry(QRect(80, 80, 624, 468))
        self.crimea.setPixmap(QPixmap(u"region/crimea.png"))

        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Alerts", u"Alerts", None))
        self.zaporizha.setText("")
        self.kherson.setText("")
        self.mykolaiv.setText("")
        self.odesa.setText("")
        self.vinnytsia.setText("")
        self.khmelnytskyi.setText("")
        self.chernivts.setText("")
        self.ivanoFrankivsk.setText("")
        self.zakarpattia.setText("")
        self.lviv.setText("")
        self.ternopil.setText("")
        self.volyn.setText("")
        self.rivne.setText("")
        self.zhytomyr.setText("")
        self.kyivRegion.setText("")
        self.kyiv.setText("")
        self.chernihiv.setText("")
        self.sumy.setText("")
        self.poltava.setText("")
        self.cherkasy.setText("")
        self.kirovohrad.setText("")
        self.dnipropetrovsk.setText("")
        self.kharkiv.setText("")
        self.luhansk.setText("")
        self.donetsk.setText("")
        self.crimea.setText("")
    # retranslateUi

