# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QSizePolicy, QWidget)

class Ui_Widget(object):
    def setupUi(self, Widget):
        if not Widget.objectName():
            Widget.setObjectName(u"Widget")
        Widget.resize(793, 594)
        self.zaporizha = QLabel(Widget)
        self.zaporizha.setObjectName(u"zaporizha")
        self.zaporizha.setGeometry(QRect(80, 80, 624, 468))
        self.zaporizha.setLineWidth(0)
        self.zaporizha.setPixmap(QPixmap(u"region/zaporizha_alert.png"))
        self.kherson = QLabel(Widget)
        self.kherson.setObjectName(u"kherson")
        self.kherson.setGeometry(QRect(80, 80, 624, 468))
        self.kherson.setMidLineWidth(5)
        self.kherson.setPixmap(QPixmap(u"region/kherson_alert.png"))
        self.mykolaiv = QLabel(Widget)
        self.mykolaiv.setObjectName(u"mykolaiv")
        self.mykolaiv.setGeometry(QRect(80, 80, 624, 468))
        self.mykolaiv.setPixmap(QPixmap(u"region/mykolaiv_alert.png"))
        self.odesa = QLabel(Widget)
        self.odesa.setObjectName(u"odesa")
        self.odesa.setGeometry(QRect(80, 80, 624, 468))
        self.odesa.setPixmap(QPixmap(u"region/odesa_alert.png"))
        self.vinnytsia = QLabel(Widget)
        self.vinnytsia.setObjectName(u"vinnytsia")
        self.vinnytsia.setGeometry(QRect(80, 80, 624, 468))
        self.vinnytsia.setPixmap(QPixmap(u"region/vinnytsia_alert.png"))
        self.khmelnytskyi = QLabel(Widget)
        self.khmelnytskyi.setObjectName(u"khmelnytskyi")
        self.khmelnytskyi.setGeometry(QRect(80, 80, 624, 468))
        self.khmelnytskyi.setPixmap(QPixmap(u"region/khmelnytskyi_alert.png"))
        self.chernivtsi = QLabel(Widget)
        self.chernivtsi.setObjectName(u"chernivtsi")
        self.chernivtsi.setGeometry(QRect(80, 80, 624, 468))
        self.chernivtsi.setPixmap(QPixmap(u"region/chernivtsi_alert.png"))
        self.ivanoFrankivsk = QLabel(Widget)
        self.ivanoFrankivsk.setObjectName(u"ivanoFrankivsk")
        self.ivanoFrankivsk.setGeometry(QRect(80, 80, 624, 468))
        self.ivanoFrankivsk.setPixmap(QPixmap(u"region/ivano-frankivsk_alert.png"))
        self.zakarpattia = QLabel(Widget)
        self.zakarpattia.setObjectName(u"zakarpattia")
        self.zakarpattia.setGeometry(QRect(80, 80, 624, 468))
        self.zakarpattia.setPixmap(QPixmap(u"region/zakarpattia_alert.png"))
        self.lviv = QLabel(Widget)
        self.lviv.setObjectName(u"lviv")
        self.lviv.setGeometry(QRect(80, 80, 624, 468))
        self.lviv.setPixmap(QPixmap(u"region/lviv_alert.png"))
        self.ternopil = QLabel(Widget)
        self.ternopil.setObjectName(u"ternopil")
        self.ternopil.setGeometry(QRect(80, 80, 624, 468))
        self.ternopil.setPixmap(QPixmap(u"region/ternopil_alert.png"))
        self.volyn = QLabel(Widget)
        self.volyn.setObjectName(u"volyn")
        self.volyn.setGeometry(QRect(80, 80, 624, 468))
        self.volyn.setPixmap(QPixmap(u"region/volyn_alert.png"))
        self.rivne = QLabel(Widget)
        self.rivne.setObjectName(u"rivne")
        self.rivne.setGeometry(QRect(80, 80, 624, 468))
        self.rivne.setPixmap(QPixmap(u"region/rivne_alert.png"))
        self.zhytomyr = QLabel(Widget)
        self.zhytomyr.setObjectName(u"zhytomyr")
        self.zhytomyr.setGeometry(QRect(80, 80, 624, 468))
        self.zhytomyr.setPixmap(QPixmap(u"region/zhytomyr_alert.png"))
        self.kyivRegion = QLabel(Widget)
        self.kyivRegion.setObjectName(u"kyivRegion")
        self.kyivRegion.setGeometry(QRect(80, 80, 624, 468))
        self.kyivRegion.setPixmap(QPixmap(u"region/kyiv-region_alert.png"))
        self.kyiv = QLabel(Widget)
        self.kyiv.setObjectName(u"kyiv")
        self.kyiv.setGeometry(QRect(80, 80, 624, 468))
        self.kyiv.setPixmap(QPixmap(u"region/kyiv_alert.png"))
        self.chernihiv = QLabel(Widget)
        self.chernihiv.setObjectName(u"chernihiv")
        self.chernihiv.setGeometry(QRect(80, 80, 624, 468))
        self.chernihiv.setPixmap(QPixmap(u"region/chernihiv_alert.png"))
        self.sumy = QLabel(Widget)
        self.sumy.setObjectName(u"sumy")
        self.sumy.setGeometry(QRect(80, 80, 624, 468))
        self.sumy.setPixmap(QPixmap(u"region/sumy_alert.png"))
        self.poltava = QLabel(Widget)
        self.poltava.setObjectName(u"poltava")
        self.poltava.setGeometry(QRect(80, 80, 624, 468))
        self.poltava.setPixmap(QPixmap(u"region/poltava_alert.png"))
        self.cherkasy = QLabel(Widget)
        self.cherkasy.setObjectName(u"cherkasy")
        self.cherkasy.setGeometry(QRect(80, 80, 624, 468))
        self.cherkasy.setPixmap(QPixmap(u"region/cherkasy_alert.png"))
        self.kirovohrad = QLabel(Widget)
        self.kirovohrad.setObjectName(u"kirovohrad")
        self.kirovohrad.setGeometry(QRect(80, 80, 624, 468))
        self.kirovohrad.setPixmap(QPixmap(u"region/kirovohrad_alert.png"))
        self.dnipropetrovsk = QLabel(Widget)
        self.dnipropetrovsk.setObjectName(u"dnipropetrovsk")
        self.dnipropetrovsk.setGeometry(QRect(80, 80, 624, 468))
        self.dnipropetrovsk.setPixmap(QPixmap(u"region/dnipropetrovsk_alert.png"))
        self.kharkiv = QLabel(Widget)
        self.kharkiv.setObjectName(u"kharkiv")
        self.kharkiv.setGeometry(QRect(80, 80, 624, 468))
        self.kharkiv.setPixmap(QPixmap(u"region/kharkiv_alert.png"))
        self.luhansk = QLabel(Widget)
        self.luhansk.setObjectName(u"luhansk")
        self.luhansk.setGeometry(QRect(80, 80, 624, 468))
        self.luhansk.setPixmap(QPixmap(u"region/luhansk_alert.png"))
        self.donetsk = QLabel(Widget)
        self.donetsk.setObjectName(u"donetsk")
        self.donetsk.setGeometry(QRect(80, 80, 624, 468))
        self.donetsk.setPixmap(QPixmap(u"region/donetsk_alert.png"))
        self.crimea = QLabel(Widget)
        self.crimea.setObjectName(u"crimea")
        self.crimea.setGeometry(QRect(80, 80, 624, 468))
        self.crimea.setPixmap(QPixmap(u"region/crimea_alert.png"))
        self.Ukraine = QLabel(Widget)
        self.Ukraine.setObjectName(u"Ukraine")
        self.Ukraine.setGeometry(QRect(80, 80, 624, 468))
        self.Ukraine.setToolTipDuration(1)
        self.Ukraine.setPixmap(QPixmap(u"region/ua-02.png"))
        self.label = QLabel(Widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(450, 400, 71, 16))

        self.zaporizha.hide()
        self.kherson.hide()
        self.mykolaiv.hide()
        self.odesa.hide()
        self.vinnytsia.hide()
        self.khmelnytskyi.hide()
        self.chernivtsi.hide()
        self.ivanoFrankivsk.hide()
        self.zakarpattia.hide()
        self.lviv.hide()
        self.ternopil.hide()
        self.volyn.hide()
        self.rivne.hide()
        self.zhytomyr.hide()
        self.kyivRegion.hide()
        self.kyiv.hide()
        self.chernihiv.hide()
        self.sumy.hide()
        self.poltava.hide()
        self.cherkasy.hide()
        self.kirovohrad.hide()
        self.dnipropetrovsk.hide()
        self.kharkiv.hide()
        self.luhansk.hide()
        self.donetsk.hide()
        self.crimea.hide()


        font = QFont()
        font.setPointSize(7)
        self.label.setFont(font)
        self.label_2 = QLabel(Widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(510, 370, 61, 16))
        self.label_2.setFont(font)
        self.label_3 = QLabel(Widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(580, 340, 61, 16))
        self.label_3.setFont(font)
        self.label_4 = QLabel(Widget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(620, 280, 61, 16))
        self.label_4.setFont(font)
        self.label_5 = QLabel(Widget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(470, 450, 49, 16))
        self.label_5.setFont(font)
        self.label_6 = QLabel(Widget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(540, 250, 61, 16))
        self.label_6.setFont(font)
        self.label_7 = QLabel(Widget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(480, 310, 71, 16))
        self.label_7.setFont(font)
        self.label_8 = QLabel(Widget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(390, 360, 61, 16))
        self.label_8.setFont(font)
        self.label_9 = QLabel(Widget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(350, 380, 49, 16))
        self.label_9.setFont(font)
        self.label_10 = QLabel(Widget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(390, 310, 71, 16))
        self.label_10.setFont(font)
        self.label_11 = QLabel(Widget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(460, 250, 49, 16))
        self.label_11.setFont(font)
        self.label_12 = QLabel(Widget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(470, 190, 49, 16))
        self.label_12.setFont(font)
        self.label_13 = QLabel(Widget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(390, 170, 61, 16))
        self.label_13.setFont(font)
        self.label_14 = QLabel(Widget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(350, 240, 49, 16))
        self.label_14.setFont(font)
        self.label_15 = QLabel(Widget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(360, 280, 49, 16))
        self.label_15.setFont(font)
        self.label_16 = QLabel(Widget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(290, 300, 49, 16))
        self.label_16.setFont(font)
        self.label_17 = QLabel(Widget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(280, 200, 61, 16))
        self.label_17.setFont(font)
        self.label_18 = QLabel(Widget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(240, 260, 41, 21))
        self.label_18.setFont(font)
        self.label_18.setMidLineWidth(2)
        self.label_18.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_19 = QLabel(Widget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(170, 180, 49, 16))
        self.label_19.setFont(font)
        self.label_20 = QLabel(Widget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(230, 160, 49, 31))
        self.label_20.setFont(font)
        self.label_21 = QLabel(Widget)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(200, 260, 51, 31))
        self.label_21.setFont(font)
        self.label_22 = QLabel(Widget)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(140, 250, 49, 16))
        self.label_22.setFont(font)
        self.label_23 = QLabel(Widget)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(210, 310, 49, 31))
        self.label_23.setFont(font)
        self.label_24 = QLabel(Widget)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(120, 310, 49, 21))
        self.label_24.setFont(font)
        self.label_25 = QLabel(Widget)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(170, 290, 49, 31))
        self.label_25.setFont(font)

        self.retranslateUi(Widget)

        QMetaObject.connectSlotsByName(Widget)
    # setupUi

    def retranslateUi(self, Widget):
        Widget.setWindowTitle(QCoreApplication.translate("Alerts", u"Alerts", None))
        self.zaporizha.setText("")
        self.kherson.setText("")
        self.mykolaiv.setText("")
        self.odesa.setText("")
        self.vinnytsia.setText("")
        self.khmelnytskyi.setText("")
        self.chernivtsi.setText("")
        self.ivanoFrankivsk.setText("")
        self.zakarpattia.setText("")
        self.lviv.setText("")
        self.ternopil.setText("")
        self.volyn.setText("")
        self.rivne.setText("")
        self.zhytomyr.setText("")
        self.kyivRegion.setText("")
        self.kyiv.setText("")
        self.chernihiv.setText("")
        self.sumy.setText("")
        self.poltava.setText("")
        self.cherkasy.setText("")
        self.kirovohrad.setText("")
        self.dnipropetrovsk.setText("")
        self.kharkiv.setText("")
        self.luhansk.setText("")
        self.donetsk.setText("")
        self.crimea.setText("")
        self.Ukraine.setText("")
        self.label.setText(QCoreApplication.translate("Widget", u"\u0425\u0435\u0440\u0441\u043e\u043d\u0441\u044c\u043a\u0430", None))
        self.label_2.setText(QCoreApplication.translate("Widget", u"\u0417\u0430\u043f\u043e\u0440\u0456\u0437\u044c\u043a\u0430", None))
        self.label_3.setText(QCoreApplication.translate("Widget", u"\u0414\u043e\u043d\u0435\u0446\u044c\u043a\u0430", None))
        self.label_4.setText(QCoreApplication.translate("Widget", u"\u041b\u0443\u0433\u0430\u043d\u0441\u044c\u043a\u0430", None))
        self.label_5.setText(QCoreApplication.translate("Widget", u"\u0410\u0420 \u041a\u0440\u0438\u043c", None))
        self.label_6.setText(QCoreApplication.translate("Widget", u"\u0425\u0430\u0440\u043a\u0456\u0432\u0441\u044c\u043a\u0430", None))
        self.label_7.setText(QCoreApplication.translate("Widget", u"\u0414\u043d\u0456\u043f\u0440\u043e\u043f\u0435\u0442\u0440\u043e\u0441\u044c\u043a\u0430", None))
        self.label_8.setText(QCoreApplication.translate("Widget", u"\u041c\u0438\u043a\u043e\u043b\u0430\u0457\u0432\u0441\u044c\u043a\u0430", None))
        self.label_9.setText(QCoreApplication.translate("Widget", u"\u041e\u0434\u0435\u0441\u044c\u043a\u0430", None))
        self.label_10.setText(QCoreApplication.translate("Widget", u"\u041a\u0456\u0440\u043e\u0432\u043e\u0433\u0440\u0430\u0434\u0441\u044c\u043a\u0430", None))
        self.label_11.setText(QCoreApplication.translate("Widget", u"\u041f\u043e\u043b\u0442\u0430\u0432\u0441\u044c\u043a\u0430", None))
        self.label_12.setText(QCoreApplication.translate("Widget", u"\u0421\u0443\u043c\u0441\u044c\u043a\u0430", None))
        self.label_13.setText(QCoreApplication.translate("Widget", u"\u0427\u0435\u0440\u043d\u0456\u0433\u0456\u0432\u0441\u044c\u043a\u0430", None))
        self.label_14.setText(QCoreApplication.translate("Widget", u"\u041a\u0438\u0457\u0432\u0441\u044c\u043a\u0430", None))
        self.label_15.setText(QCoreApplication.translate("Widget", u"\u0427\u0435\u0440\u043a\u0430\u0441\u044c\u043a\u0430", None))
        self.label_16.setText(QCoreApplication.translate("Widget", u"\u0412\u0456\u043d\u043d\u0438\u0446\u044c\u043a\u0430", None))
        self.label_17.setText(QCoreApplication.translate("Widget", u"\u0416\u0438\u0442\u043e\u043c\u0438\u0440\u0441\u044c\u043a\u0430", None))
        self.label_18.setText(QCoreApplication.translate("Widget", u"\u0425\u043c\u0435\u043b\u044c\u043d\u0438-\n"
"\u0446\u044c\u043a\u0430", None))
        self.label_19.setText(QCoreApplication.translate("Widget", u"\u0412\u043e\u043b\u0438\u043d\u0441\u044c\u043a\u0430", None))
        self.label_20.setText(QCoreApplication.translate("Widget", u"\u0420\u0456\u0432\u043d\u0435\u043d-\n"
"\u0441\u044c\u043a\u0430", None))
        self.label_21.setText(QCoreApplication.translate("Widget", u"\u0422\u0435\u0440\u043d\u043e-\n"
"\u043f\u0456n\u043b\u044c\u0441\u043a\u0430", None))
        self.label_22.setText(QCoreApplication.translate("Widget", u"\u041b\u044c\u0432\u0456\u0432\u0441\u044c\u043a\u0430", None))
        self.label_23.setText(QCoreApplication.translate("Widget", u"   \u0427\u0435\u0440\u043d\u0456-\n"
"\u0432\u0435\u0446\u044c\u043a\u0430", None))
        self.label_24.setText(QCoreApplication.translate("Widget", u"\u0417\u0430\u043a\u0430\u0440-\n"
"\u043f\u0430\u0442\u0441\u044c\u043a\u0430", None))
        self.label_25.setText(QCoreApplication.translate("Widget", u"I\u0432\u0430\u043d\u043e-\n"
"\u0424\u0440\u0430\u043d\u043a", None))
    # retranslateUi

